#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

use Illuminate\Contracts\Console\Kernel;
use Illuminate\Contracts\Debug\ExceptionHandler;
use Laravel\Lumen\Application;
use Symfony\Component\Console\Input\ArgvInput;
use Symfony\Component\Console\Output\ConsoleOutput;

(new Dotenv\Dotenv(__DIR__ . '/env'))->load();

$app = new Application();
$app->register(App\Providers\AppServiceProvider::class);

$app->singleton(ExceptionHandler::class, App\Exceptions\Handler::class);
$app->singleton(Kernel::class, App\Console\Kernel::class);

$kernel = $app->make(Kernel::class);

exit($kernel->handle(new ArgvInput, new ConsoleOutput));
